name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.OC_DOCKER_REGISTORY }}/poc-project/my-app:latest
    - name: Authenticate Docker
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.API_TOKEN }} ${{ secrets.OC_DOCKER_REGISTORY }}
    - name: Pushing Docker Image
      run: docker push ${{ secrets.OC_DOCKER_REGISTORY }}/poc-project/my-app:latest
